// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mickael-carl/sophons/pkg/exec (interfaces: commandExecutor)
//
// Generated by this command:
//
//	mockgen -destination=mock_command_executor_test.go -package=exec . commandExecutor
//

// Package exec is a generated GoMock package.
package exec

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcommandExecutor is a mock of commandExecutor interface.
type MockcommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockcommandExecutorMockRecorder
	isgomock struct{}
}

// MockcommandExecutorMockRecorder is the mock recorder for MockcommandExecutor.
type MockcommandExecutorMockRecorder struct {
	mock *MockcommandExecutor
}

// NewMockcommandExecutor creates a new mock instance.
func NewMockcommandExecutor(ctrl *gomock.Controller) *MockcommandExecutor {
	mock := &MockcommandExecutor{ctrl: ctrl}
	mock.recorder = &MockcommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommandExecutor) EXPECT() *MockcommandExecutorMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockcommandExecutor) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockcommandExecutorMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockcommandExecutor)(nil).Run))
}

// SetDir mocks base method.
func (m *MockcommandExecutor) SetDir(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDir", arg0)
}

// SetDir indicates an expected call of SetDir.
func (mr *MockcommandExecutorMockRecorder) SetDir(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDir", reflect.TypeOf((*MockcommandExecutor)(nil).SetDir), arg0)
}

// SetStderr mocks base method.
func (m *MockcommandExecutor) SetStderr(arg0 io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", arg0)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockcommandExecutorMockRecorder) SetStderr(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockcommandExecutor)(nil).SetStderr), arg0)
}

// SetStdin mocks base method.
func (m *MockcommandExecutor) SetStdin(arg0 io.Reader) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdin", arg0)
}

// SetStdin indicates an expected call of SetStdin.
func (mr *MockcommandExecutorMockRecorder) SetStdin(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdin", reflect.TypeOf((*MockcommandExecutor)(nil).SetStdin), arg0)
}

// SetStdout mocks base method.
func (m *MockcommandExecutor) SetStdout(arg0 io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", arg0)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockcommandExecutorMockRecorder) SetStdout(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockcommandExecutor)(nil).SetStdout), arg0)
}
