// Code generated by MockGen. DO NOT EDIT.
// Source: apt_client.go
//
// Generated by this command:
//
//	mockgen -source=apt_client.go -destination=mock_apt_client_test.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	apt "github.com/arduino/go-apt-client"
	gomock "go.uber.org/mock/gomock"
)

// MockaptClient is a mock of aptClient interface.
type MockaptClient struct {
	ctrl     *gomock.Controller
	recorder *MockaptClientMockRecorder
	isgomock struct{}
}

// MockaptClientMockRecorder is the mock recorder for MockaptClient.
type MockaptClientMockRecorder struct {
	mock *MockaptClient
}

// NewMockaptClient creates a new mock instance.
func NewMockaptClient(ctrl *gomock.Controller) *MockaptClient {
	mock := &MockaptClient{ctrl: ctrl}
	mock.recorder = &MockaptClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaptClient) EXPECT() *MockaptClientMockRecorder {
	return m.recorder
}

// AddRepository mocks base method.
func (m *MockaptClient) AddRepository(repo *apt.Repository, path, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRepository", repo, path, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRepository indicates an expected call of AddRepository.
func (mr *MockaptClientMockRecorder) AddRepository(repo, path, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRepository", reflect.TypeOf((*MockaptClient)(nil).AddRepository), repo, path, filename)
}

// CheckForUpdates mocks base method.
func (m *MockaptClient) CheckForUpdates() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForUpdates")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForUpdates indicates an expected call of CheckForUpdates.
func (mr *MockaptClientMockRecorder) CheckForUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForUpdates", reflect.TypeOf((*MockaptClient)(nil).CheckForUpdates))
}

// Clean mocks base method.
func (m *MockaptClient) Clean() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockaptClientMockRecorder) Clean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockaptClient)(nil).Clean))
}

// DistUpgrade mocks base method.
func (m *MockaptClient) DistUpgrade() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistUpgrade")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistUpgrade indicates an expected call of DistUpgrade.
func (mr *MockaptClientMockRecorder) DistUpgrade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistUpgrade", reflect.TypeOf((*MockaptClient)(nil).DistUpgrade))
}

// Install mocks base method.
func (m *MockaptClient) Install(pkgs ...*apt.Package) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range pkgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Install", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockaptClientMockRecorder) Install(pkgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockaptClient)(nil).Install), pkgs...)
}

// ListInstalled mocks base method.
func (m *MockaptClient) ListInstalled() ([]*apt.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstalled")
	ret0, _ := ret[0].([]*apt.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstalled indicates an expected call of ListInstalled.
func (mr *MockaptClientMockRecorder) ListInstalled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstalled", reflect.TypeOf((*MockaptClient)(nil).ListInstalled))
}

// ParseAPTConfigFolder mocks base method.
func (m *MockaptClient) ParseAPTConfigFolder(path string) (apt.RepositoryList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAPTConfigFolder", path)
	ret0, _ := ret[0].(apt.RepositoryList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAPTConfigFolder indicates an expected call of ParseAPTConfigFolder.
func (mr *MockaptClientMockRecorder) ParseAPTConfigFolder(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAPTConfigFolder", reflect.TypeOf((*MockaptClient)(nil).ParseAPTConfigFolder), path)
}

// ParseAPTConfigLine mocks base method.
func (m *MockaptClient) ParseAPTConfigLine(line string) *apt.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAPTConfigLine", line)
	ret0, _ := ret[0].(*apt.Repository)
	return ret0
}

// ParseAPTConfigLine indicates an expected call of ParseAPTConfigLine.
func (mr *MockaptClientMockRecorder) ParseAPTConfigLine(line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAPTConfigLine", reflect.TypeOf((*MockaptClient)(nil).ParseAPTConfigLine), line)
}

// Remove mocks base method.
func (m *MockaptClient) Remove(pkgs ...*apt.Package) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range pkgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Remove", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockaptClientMockRecorder) Remove(pkgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockaptClient)(nil).Remove), pkgs...)
}

// RemoveRepository mocks base method.
func (m *MockaptClient) RemoveRepository(repo *apt.Repository, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRepository", repo, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRepository indicates an expected call of RemoveRepository.
func (mr *MockaptClientMockRecorder) RemoveRepository(repo, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRepository", reflect.TypeOf((*MockaptClient)(nil).RemoveRepository), repo, path)
}

// UpgradeAll mocks base method.
func (m *MockaptClient) UpgradeAll() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeAll")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeAll indicates an expected call of UpgradeAll.
func (mr *MockaptClientMockRecorder) UpgradeAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeAll", reflect.TypeOf((*MockaptClient)(nil).UpgradeAll))
}
