// Code generated by MockGen. DO NOT EDIT.
// Source: apt_client.go
//
// Generated by this command:
//
//	mockgen -source=apt_client.go -destination=mock_apt_client_test.go -package=exec
//

// Package exec is a generated GoMock package.
package exec

import (
	reflect "reflect"

	apt "github.com/arduino/go-apt-client"
	gomock "go.uber.org/mock/gomock"
)

// MockaptClient is a mock of aptClient interface.
type MockaptClient struct {
	ctrl     *gomock.Controller
	recorder *MockaptClientMockRecorder
	isgomock struct{}
}

// MockaptClientMockRecorder is the mock recorder for MockaptClient.
type MockaptClientMockRecorder struct {
	mock *MockaptClient
}

// NewMockaptClient creates a new mock instance.
func NewMockaptClient(ctrl *gomock.Controller) *MockaptClient {
	mock := &MockaptClient{ctrl: ctrl}
	mock.recorder = &MockaptClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaptClient) EXPECT() *MockaptClientMockRecorder {
	return m.recorder
}

// CheckForUpdates mocks base method.
func (m *MockaptClient) CheckForUpdates() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForUpdates")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForUpdates indicates an expected call of CheckForUpdates.
func (mr *MockaptClientMockRecorder) CheckForUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForUpdates", reflect.TypeOf((*MockaptClient)(nil).CheckForUpdates))
}

// Clean mocks base method.
func (m *MockaptClient) Clean() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockaptClientMockRecorder) Clean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockaptClient)(nil).Clean))
}

// DistUpgrade mocks base method.
func (m *MockaptClient) DistUpgrade() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistUpgrade")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistUpgrade indicates an expected call of DistUpgrade.
func (mr *MockaptClientMockRecorder) DistUpgrade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistUpgrade", reflect.TypeOf((*MockaptClient)(nil).DistUpgrade))
}

// Install mocks base method.
func (m *MockaptClient) Install(pkgs ...*apt.Package) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range pkgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Install", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockaptClientMockRecorder) Install(pkgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockaptClient)(nil).Install), pkgs...)
}

// ListInstalled mocks base method.
func (m *MockaptClient) ListInstalled() ([]*apt.Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstalled")
	ret0, _ := ret[0].([]*apt.Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstalled indicates an expected call of ListInstalled.
func (mr *MockaptClientMockRecorder) ListInstalled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstalled", reflect.TypeOf((*MockaptClient)(nil).ListInstalled))
}

// Remove mocks base method.
func (m *MockaptClient) Remove(pkgs ...*apt.Package) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range pkgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Remove", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockaptClientMockRecorder) Remove(pkgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockaptClient)(nil).Remove), pkgs...)
}

// UpgradeAll mocks base method.
func (m *MockaptClient) UpgradeAll() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeAll")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeAll indicates an expected call of UpgradeAll.
func (mr *MockaptClientMockRecorder) UpgradeAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeAll", reflect.TypeOf((*MockaptClient)(nil).UpgradeAll))
}
