// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/apt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Apt manages packages with the apt package manager.
//
//	@meta{
//	  "deviations": [
//	    "`state` only supports `present`, `latest` and `absent`",
//	    "version strings in package names are not supported",
//	  ]
//	}
type Apt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"allow_change_held_packages"
	AllowChangeHeldPackages bool `protobuf:"varint,1,opt,name=allow_change_held_packages,json=allowChangeHeldPackages,proto3" json:"allow_change_held_packages,omitempty" yaml:"allow_change_held_packages"`
	// @inject_tag: yaml:"allow_downgrade"
	AllowDowngrade bool `protobuf:"varint,2,opt,name=allow_downgrade,json=allowDowngrade,proto3" json:"allow_downgrade,omitempty" yaml:"allow_downgrade"`
	// @inject_tag: yaml:"allow_unauthenticated"
	AllowUnauthenticated bool `protobuf:"varint,3,opt,name=allow_unauthenticated,json=allowUnauthenticated,proto3" json:"allow_unauthenticated,omitempty" yaml:"allow_unauthenticated"`
	// @inject_tag: yaml:"auto_install_module_deps"
	AutoInstallModuleDeps *bool `protobuf:"varint,4,opt,name=auto_install_module_deps,json=autoInstallModuleDeps,proto3,oneof" json:"auto_install_module_deps,omitempty" yaml:"auto_install_module_deps"`
	// @inject_tag: yaml:"autoclean"
	Autoclean bool `protobuf:"varint,5,opt,name=autoclean,proto3" json:"autoclean,omitempty" yaml:"autoclean"`
	// @inject_tag: yaml:"autoremove"
	Autoremove bool `protobuf:"varint,6,opt,name=autoremove,proto3" json:"autoremove,omitempty" yaml:"autoremove"`
	// @inject_tag: yaml:"cache_valid_time" sophons:"implemented"
	CacheValidTime *uint64 `protobuf:"varint,7,opt,name=cache_valid_time,json=cacheValidTime,proto3,oneof" json:"cache_valid_time,omitempty" yaml:"cache_valid_time" sophons:"implemented"`
	// @inject_tag: yaml:"clean" sophons:"implemented"
	Clean bool `protobuf:"varint,8,opt,name=clean,proto3" json:"clean,omitempty" yaml:"clean" sophons:"implemented"`
	// @inject_tag: yaml:"deb"
	Deb string `protobuf:"bytes,9,opt,name=deb,proto3" json:"deb,omitempty" yaml:"deb"`
	// @inject_tag: yaml:"default_release"
	DefaultRelease string `protobuf:"bytes,10,opt,name=default_release,json=defaultRelease,proto3" json:"default_release,omitempty" yaml:"default_release"`
	// @inject_tag: yaml:"dpkg_options"
	DpkgOptions string `protobuf:"bytes,11,opt,name=dpkg_options,json=dpkgOptions,proto3" json:"dpkg_options,omitempty" yaml:"dpkg_options"`
	// @inject_tag: yaml:"fail_on_autoremove"
	FailOnAutoremove bool `protobuf:"varint,12,opt,name=fail_on_autoremove,json=failOnAutoremove,proto3" json:"fail_on_autoremove,omitempty" yaml:"fail_on_autoremove"`
	// @inject_tag: yaml:"force"
	Force bool `protobuf:"varint,13,opt,name=force,proto3" json:"force,omitempty" yaml:"force"`
	// @inject_tag: yaml:"force_apt_get"
	ForceAptGet bool `protobuf:"varint,14,opt,name=force_apt_get,json=forceAptGet,proto3" json:"force_apt_get,omitempty" yaml:"force_apt_get"`
	// @inject_tag: yaml:"install_recommends"
	InstallRecommends bool `protobuf:"varint,15,opt,name=install_recommends,json=installRecommends,proto3" json:"install_recommends,omitempty" yaml:"install_recommends"`
	// @inject_tag: yaml:"lock_timeout"
	LockTimeout int64 `protobuf:"varint,16,opt,name=lock_timeout,json=lockTimeout,proto3" json:"lock_timeout,omitempty" yaml:"lock_timeout"`
	// @inject_tag: yaml:"name" sophons:"implemented"
	Name *PackageList `protobuf:"bytes,17,opt,name=name,proto3" json:"name,omitempty" yaml:"name" sophons:"implemented"`
	// @inject_tag: yaml:"only_upgrade"
	OnlyUpgrade bool `protobuf:"varint,18,opt,name=only_upgrade,json=onlyUpgrade,proto3" json:"only_upgrade,omitempty" yaml:"only_upgrade"`
	// @inject_tag: yaml:"policy_rc_d"
	PolicyRcD int64 `protobuf:"varint,19,opt,name=policy_rc_d,json=policyRcD,proto3" json:"policy_rc_d,omitempty" yaml:"policy_rc_d"`
	// @inject_tag: yaml:"purge"
	Purge bool `protobuf:"varint,20,opt,name=purge,proto3" json:"purge,omitempty" yaml:"purge"`
	// @inject_tag: yaml:"state" sophons:"implemented"
	State string `protobuf:"bytes,21,opt,name=state,proto3" json:"state,omitempty" yaml:"state" sophons:"implemented"`
	// @inject_tag: yaml:"update_cache" sophons:"implemented"
	UpdateCache *bool `protobuf:"varint,22,opt,name=update_cache,json=updateCache,proto3,oneof" json:"update_cache,omitempty" yaml:"update_cache" sophons:"implemented"`
	// @inject_tag: yaml:"update_cache_retries"
	UpdateCacheRetries uint64 `protobuf:"varint,23,opt,name=update_cache_retries,json=updateCacheRetries,proto3" json:"update_cache_retries,omitempty" yaml:"update_cache_retries"`
	// @inject_tag: yaml:"update_cache_retry_max_delay"
	UpdateCacheRetryMaxDelay uint64 `protobuf:"varint,24,opt,name=update_cache_retry_max_delay,json=updateCacheRetryMaxDelay,proto3" json:"update_cache_retry_max_delay,omitempty" yaml:"update_cache_retry_max_delay"`
	// @inject_tag: yaml:"upgrade" sophons:"implemented"
	Upgrade       string `protobuf:"bytes,25,opt,name=upgrade,proto3" json:"upgrade,omitempty" yaml:"upgrade" sophons:"implemented"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Apt) Reset() {
	*x = Apt{}
	mi := &file_proto_apt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apt) ProtoMessage() {}

func (x *Apt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apt.ProtoReflect.Descriptor instead.
func (*Apt) Descriptor() ([]byte, []int) {
	return file_proto_apt_proto_rawDescGZIP(), []int{0}
}

func (x *Apt) GetAllowChangeHeldPackages() bool {
	if x != nil {
		return x.AllowChangeHeldPackages
	}
	return false
}

func (x *Apt) GetAllowDowngrade() bool {
	if x != nil {
		return x.AllowDowngrade
	}
	return false
}

func (x *Apt) GetAllowUnauthenticated() bool {
	if x != nil {
		return x.AllowUnauthenticated
	}
	return false
}

func (x *Apt) GetAutoInstallModuleDeps() bool {
	if x != nil && x.AutoInstallModuleDeps != nil {
		return *x.AutoInstallModuleDeps
	}
	return false
}

func (x *Apt) GetAutoclean() bool {
	if x != nil {
		return x.Autoclean
	}
	return false
}

func (x *Apt) GetAutoremove() bool {
	if x != nil {
		return x.Autoremove
	}
	return false
}

func (x *Apt) GetCacheValidTime() uint64 {
	if x != nil && x.CacheValidTime != nil {
		return *x.CacheValidTime
	}
	return 0
}

func (x *Apt) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

func (x *Apt) GetDeb() string {
	if x != nil {
		return x.Deb
	}
	return ""
}

func (x *Apt) GetDefaultRelease() string {
	if x != nil {
		return x.DefaultRelease
	}
	return ""
}

func (x *Apt) GetDpkgOptions() string {
	if x != nil {
		return x.DpkgOptions
	}
	return ""
}

func (x *Apt) GetFailOnAutoremove() bool {
	if x != nil {
		return x.FailOnAutoremove
	}
	return false
}

func (x *Apt) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *Apt) GetForceAptGet() bool {
	if x != nil {
		return x.ForceAptGet
	}
	return false
}

func (x *Apt) GetInstallRecommends() bool {
	if x != nil {
		return x.InstallRecommends
	}
	return false
}

func (x *Apt) GetLockTimeout() int64 {
	if x != nil {
		return x.LockTimeout
	}
	return 0
}

func (x *Apt) GetName() *PackageList {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Apt) GetOnlyUpgrade() bool {
	if x != nil {
		return x.OnlyUpgrade
	}
	return false
}

func (x *Apt) GetPolicyRcD() int64 {
	if x != nil {
		return x.PolicyRcD
	}
	return 0
}

func (x *Apt) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

func (x *Apt) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Apt) GetUpdateCache() bool {
	if x != nil && x.UpdateCache != nil {
		return *x.UpdateCache
	}
	return false
}

func (x *Apt) GetUpdateCacheRetries() uint64 {
	if x != nil {
		return x.UpdateCacheRetries
	}
	return 0
}

func (x *Apt) GetUpdateCacheRetryMaxDelay() uint64 {
	if x != nil {
		return x.UpdateCacheRetryMaxDelay
	}
	return 0
}

func (x *Apt) GetUpgrade() string {
	if x != nil {
		return x.Upgrade
	}
	return ""
}

type PackageList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"items"
	Items         []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" yaml:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageList) Reset() {
	*x = PackageList{}
	mi := &file_proto_apt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageList) ProtoMessage() {}

func (x *PackageList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageList.ProtoReflect.Descriptor instead.
func (*PackageList) Descriptor() ([]byte, []int) {
	return file_proto_apt_proto_rawDescGZIP(), []int{1}
}

func (x *PackageList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_apt_proto protoreflect.FileDescriptor

const file_proto_apt_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/apt.proto\x12\x05proto\"\x87\b\n" +
	"\x03Apt\x12;\n" +
	"\x1aallow_change_held_packages\x18\x01 \x01(\bR\x17allowChangeHeldPackages\x12'\n" +
	"\x0fallow_downgrade\x18\x02 \x01(\bR\x0eallowDowngrade\x123\n" +
	"\x15allow_unauthenticated\x18\x03 \x01(\bR\x14allowUnauthenticated\x12<\n" +
	"\x18auto_install_module_deps\x18\x04 \x01(\bH\x00R\x15autoInstallModuleDeps\x88\x01\x01\x12\x1c\n" +
	"\tautoclean\x18\x05 \x01(\bR\tautoclean\x12\x1e\n" +
	"\n" +
	"autoremove\x18\x06 \x01(\bR\n" +
	"autoremove\x12-\n" +
	"\x10cache_valid_time\x18\a \x01(\x04H\x01R\x0ecacheValidTime\x88\x01\x01\x12\x14\n" +
	"\x05clean\x18\b \x01(\bR\x05clean\x12\x10\n" +
	"\x03deb\x18\t \x01(\tR\x03deb\x12'\n" +
	"\x0fdefault_release\x18\n" +
	" \x01(\tR\x0edefaultRelease\x12!\n" +
	"\fdpkg_options\x18\v \x01(\tR\vdpkgOptions\x12,\n" +
	"\x12fail_on_autoremove\x18\f \x01(\bR\x10failOnAutoremove\x12\x14\n" +
	"\x05force\x18\r \x01(\bR\x05force\x12\"\n" +
	"\rforce_apt_get\x18\x0e \x01(\bR\vforceAptGet\x12-\n" +
	"\x12install_recommends\x18\x0f \x01(\bR\x11installRecommends\x12!\n" +
	"\flock_timeout\x18\x10 \x01(\x03R\vlockTimeout\x12&\n" +
	"\x04name\x18\x11 \x01(\v2\x12.proto.PackageListR\x04name\x12!\n" +
	"\fonly_upgrade\x18\x12 \x01(\bR\vonlyUpgrade\x12\x1e\n" +
	"\vpolicy_rc_d\x18\x13 \x01(\x03R\tpolicyRcD\x12\x14\n" +
	"\x05purge\x18\x14 \x01(\bR\x05purge\x12\x14\n" +
	"\x05state\x18\x15 \x01(\tR\x05state\x12&\n" +
	"\fupdate_cache\x18\x16 \x01(\bH\x02R\vupdateCache\x88\x01\x01\x120\n" +
	"\x14update_cache_retries\x18\x17 \x01(\x04R\x12updateCacheRetries\x12>\n" +
	"\x1cupdate_cache_retry_max_delay\x18\x18 \x01(\x04R\x18updateCacheRetryMaxDelay\x12\x18\n" +
	"\aupgrade\x18\x19 \x01(\tR\aupgradeB\x1b\n" +
	"\x19_auto_install_module_depsB\x13\n" +
	"\x11_cache_valid_timeB\x0f\n" +
	"\r_update_cache\"#\n" +
	"\vPackageList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05itemsB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_apt_proto_rawDescOnce sync.Once
	file_proto_apt_proto_rawDescData []byte
)

func file_proto_apt_proto_rawDescGZIP() []byte {
	file_proto_apt_proto_rawDescOnce.Do(func() {
		file_proto_apt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apt_proto_rawDesc), len(file_proto_apt_proto_rawDesc)))
	})
	return file_proto_apt_proto_rawDescData
}

var file_proto_apt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_apt_proto_goTypes = []any{
	(*Apt)(nil),         // 0: proto.Apt
	(*PackageList)(nil), // 1: proto.PackageList
}
var file_proto_apt_proto_depIdxs = []int32{
	1, // 0: proto.Apt.name:type_name -> proto.PackageList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_apt_proto_init() }
func file_proto_apt_proto_init() {
	if File_proto_apt_proto != nil {
		return
	}
	file_proto_apt_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apt_proto_rawDesc), len(file_proto_apt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_apt_proto_goTypes,
		DependencyIndexes: file_proto_apt_proto_depIdxs,
		MessageInfos:      file_proto_apt_proto_msgTypes,
	}.Build()
	File_proto_apt_proto = out.File
	file_proto_apt_proto_goTypes = nil
	file_proto_apt_proto_depIdxs = nil
}
