// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/apt_repository.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AptRepository manages apt repositories.
type AptRepository struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"codename"
	Codename string `protobuf:"bytes,1,opt,name=codename,proto3" json:"codename,omitempty" yaml:"codename"`
	// @inject_tag: yaml:"filename"
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty" yaml:"filename"`
	// @inject_tag: yaml:"install_python_apt"
	InstallPythonApt bool `protobuf:"varint,3,opt,name=install_python_apt,json=installPythonApt,proto3" json:"install_python_apt,omitempty" yaml:"install_python_apt"`
	// @inject_tag: yaml:"mode"
	Mode string `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty" yaml:"mode"`
	// @inject_tag: yaml:"repo" sophons:"implemented"
	Repo string `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty" yaml:"repo" sophons:"implemented"`
	// @inject_tag: yaml:"state" sophons:"implemented"
	State string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty" yaml:"state" sophons:"implemented"`
	// @inject_tag: yaml:"update_cache" sophons:"implemented"
	UpdateCache *bool `protobuf:"varint,7,opt,name=update_cache,json=updateCache,proto3,oneof" json:"update_cache,omitempty" yaml:"update_cache" sophons:"implemented"`
	// @inject_tag: yaml:"update_cache_retries"
	UpdateCacheRetries uint64 `protobuf:"varint,8,opt,name=update_cache_retries,json=updateCacheRetries,proto3" json:"update_cache_retries,omitempty" yaml:"update_cache_retries"`
	// @inject_tag: yaml:"update_cache_retry_max_delay"
	UpdateCacheRetryMaxDelay uint64 `protobuf:"varint,9,opt,name=update_cache_retry_max_delay,json=updateCacheRetryMaxDelay,proto3" json:"update_cache_retry_max_delay,omitempty" yaml:"update_cache_retry_max_delay"`
	// @inject_tag: yaml:"validate_certs"
	ValidateCerts *bool `protobuf:"varint,10,opt,name=validate_certs,json=validateCerts,proto3,oneof" json:"validate_certs,omitempty" yaml:"validate_certs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AptRepository) Reset() {
	*x = AptRepository{}
	mi := &file_proto_apt_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AptRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AptRepository) ProtoMessage() {}

func (x *AptRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apt_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AptRepository.ProtoReflect.Descriptor instead.
func (*AptRepository) Descriptor() ([]byte, []int) {
	return file_proto_apt_repository_proto_rawDescGZIP(), []int{0}
}

func (x *AptRepository) GetCodename() string {
	if x != nil {
		return x.Codename
	}
	return ""
}

func (x *AptRepository) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AptRepository) GetInstallPythonApt() bool {
	if x != nil {
		return x.InstallPythonApt
	}
	return false
}

func (x *AptRepository) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AptRepository) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *AptRepository) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AptRepository) GetUpdateCache() bool {
	if x != nil && x.UpdateCache != nil {
		return *x.UpdateCache
	}
	return false
}

func (x *AptRepository) GetUpdateCacheRetries() uint64 {
	if x != nil {
		return x.UpdateCacheRetries
	}
	return 0
}

func (x *AptRepository) GetUpdateCacheRetryMaxDelay() uint64 {
	if x != nil {
		return x.UpdateCacheRetryMaxDelay
	}
	return 0
}

func (x *AptRepository) GetValidateCerts() bool {
	if x != nil && x.ValidateCerts != nil {
		return *x.ValidateCerts
	}
	return false
}

var File_proto_apt_repository_proto protoreflect.FileDescriptor

const file_proto_apt_repository_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/apt_repository.proto\x12\x05proto\"\x9d\x03\n" +
	"\rAptRepository\x12\x1a\n" +
	"\bcodename\x18\x01 \x01(\tR\bcodename\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12,\n" +
	"\x12install_python_apt\x18\x03 \x01(\bR\x10installPythonApt\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x12\n" +
	"\x04repo\x18\x05 \x01(\tR\x04repo\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12&\n" +
	"\fupdate_cache\x18\a \x01(\bH\x00R\vupdateCache\x88\x01\x01\x120\n" +
	"\x14update_cache_retries\x18\b \x01(\x04R\x12updateCacheRetries\x12>\n" +
	"\x1cupdate_cache_retry_max_delay\x18\t \x01(\x04R\x18updateCacheRetryMaxDelay\x12*\n" +
	"\x0evalidate_certs\x18\n" +
	" \x01(\bH\x01R\rvalidateCerts\x88\x01\x01B\x0f\n" +
	"\r_update_cacheB\x11\n" +
	"\x0f_validate_certsB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_apt_repository_proto_rawDescOnce sync.Once
	file_proto_apt_repository_proto_rawDescData []byte
)

func file_proto_apt_repository_proto_rawDescGZIP() []byte {
	file_proto_apt_repository_proto_rawDescOnce.Do(func() {
		file_proto_apt_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apt_repository_proto_rawDesc), len(file_proto_apt_repository_proto_rawDesc)))
	})
	return file_proto_apt_repository_proto_rawDescData
}

var file_proto_apt_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_apt_repository_proto_goTypes = []any{
	(*AptRepository)(nil), // 0: proto.AptRepository
}
var file_proto_apt_repository_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_apt_repository_proto_init() }
func file_proto_apt_repository_proto_init() {
	if File_proto_apt_repository_proto != nil {
		return
	}
	file_proto_apt_repository_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apt_repository_proto_rawDesc), len(file_proto_apt_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_apt_repository_proto_goTypes,
		DependencyIndexes: file_proto_apt_repository_proto_depIdxs,
		MessageInfos:      file_proto_apt_repository_proto_msgTypes,
	}.Build()
	File_proto_apt_repository_proto = out.File
	file_proto_apt_repository_proto_goTypes = nil
	file_proto_apt_repository_proto_depIdxs = nil
}
