// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command executes a command on the target host.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"cmd" sophons:"implemented"
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty" yaml:"cmd" sophons:"implemented"`
	// @inject_tag: yaml:"argv" sophons:"implemented"
	Argv []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty" yaml:"argv" sophons:"implemented"`
	// @inject_tag: yaml:"creates" sophons:"implemented"
	Creates string `protobuf:"bytes,3,opt,name=creates,proto3" json:"creates,omitempty" yaml:"creates" sophons:"implemented"`
	// @inject_tag: yaml:"removes" sophons:"implemented"
	Removes string `protobuf:"bytes,4,opt,name=removes,proto3" json:"removes,omitempty" yaml:"removes" sophons:"implemented"`
	// @inject_tag: yaml:"chdir" sophons:"implemented"
	Chdir string `protobuf:"bytes,5,opt,name=chdir,proto3" json:"chdir,omitempty" yaml:"chdir" sophons:"implemented"`
	// @inject_tag: yaml:"expand_argument_vars" sophons:"implemented"
	ExpandArgumentVars bool `protobuf:"varint,6,opt,name=expand_argument_vars,json=expandArgumentVars,proto3" json:"expand_argument_vars,omitempty" yaml:"expand_argument_vars" sophons:"implemented"`
	// @inject_tag: yaml:"stdin" sophons:"implemented"
	Stdin string `protobuf:"bytes,7,opt,name=stdin,proto3" json:"stdin,omitempty" yaml:"stdin" sophons:"implemented"`
	// @inject_tag: yaml:"stdin_add_newline" sophons:"implemented"
	StdinAddNewline *bool `protobuf:"varint,8,opt,name=stdin_add_newline,json=stdinAddNewline,proto3,oneof" json:"stdin_add_newline,omitempty" yaml:"stdin_add_newline" sophons:"implemented"`
	// @inject_tag: yaml:"strip_empty_ends"
	StripEmptyEnds *bool `protobuf:"varint,9,opt,name=strip_empty_ends,json=stripEmptyEnds,proto3,oneof" json:"strip_empty_ends,omitempty" yaml:"strip_empty_ends"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *Command) GetCreates() string {
	if x != nil {
		return x.Creates
	}
	return ""
}

func (x *Command) GetRemoves() string {
	if x != nil {
		return x.Removes
	}
	return ""
}

func (x *Command) GetChdir() string {
	if x != nil {
		return x.Chdir
	}
	return ""
}

func (x *Command) GetExpandArgumentVars() bool {
	if x != nil {
		return x.ExpandArgumentVars
	}
	return false
}

func (x *Command) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *Command) GetStdinAddNewline() bool {
	if x != nil && x.StdinAddNewline != nil {
		return *x.StdinAddNewline
	}
	return false
}

func (x *Command) GetStripEmptyEnds() bool {
	if x != nil && x.StripEmptyEnds != nil {
		return *x.StripEmptyEnds
	}
	return false
}

var File_proto_command_proto protoreflect.FileDescriptor

const file_proto_command_proto_rawDesc = "" +
	"\n" +
	"\x13proto/command.proto\x12\x05proto\"\xcc\x02\n" +
	"\aCommand\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x18\n" +
	"\acreates\x18\x03 \x01(\tR\acreates\x12\x18\n" +
	"\aremoves\x18\x04 \x01(\tR\aremoves\x12\x14\n" +
	"\x05chdir\x18\x05 \x01(\tR\x05chdir\x120\n" +
	"\x14expand_argument_vars\x18\x06 \x01(\bR\x12expandArgumentVars\x12\x14\n" +
	"\x05stdin\x18\a \x01(\tR\x05stdin\x12/\n" +
	"\x11stdin_add_newline\x18\b \x01(\bH\x00R\x0fstdinAddNewline\x88\x01\x01\x12-\n" +
	"\x10strip_empty_ends\x18\t \x01(\bH\x01R\x0estripEmptyEnds\x88\x01\x01B\x14\n" +
	"\x12_stdin_add_newlineB\x13\n" +
	"\x11_strip_empty_endsB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_command_proto_rawDescOnce sync.Once
	file_proto_command_proto_rawDescData []byte
)

func file_proto_command_proto_rawDescGZIP() []byte {
	file_proto_command_proto_rawDescOnce.Do(func() {
		file_proto_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)))
	})
	return file_proto_command_proto_rawDescData
}

var file_proto_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_command_proto_goTypes = []any{
	(*Command)(nil), // 0: proto.Command
}
var file_proto_command_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_command_proto_init() }
func file_proto_command_proto_init() {
	if File_proto_command_proto != nil {
		return
	}
	file_proto_command_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_command_proto_goTypes,
		DependencyIndexes: file_proto_command_proto_depIdxs,
		MessageInfos:      file_proto_command_proto_msgTypes,
	}.Build()
	File_proto_command_proto = out.File
	file_proto_command_proto_goTypes = nil
	file_proto_command_proto_depIdxs = nil
}
