// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/copy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Copy copies files from the controller to the target host.
type Copy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"content" sophons:"implemented"
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty" yaml:"content" sophons:"implemented"`
	// @inject_tag: yaml:"remote_src"
	RemoteSrc bool `protobuf:"varint,2,opt,name=remote_src,json=remoteSrc,proto3" json:"remote_src,omitempty" yaml:"remote_src"`
	// @inject_tag: yaml:"src" sophons:"implemented"
	Src string `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty" yaml:"src" sophons:"implemented"`
	// @inject_tag: yaml:"dest" sophons:"implemented"
	Dest string `protobuf:"bytes,4,opt,name=dest,proto3" json:"dest,omitempty" yaml:"dest" sophons:"implemented"`
	// @inject_tag: yaml:"attributes"
	Attributes string `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty" yaml:"attributes"`
	// @inject_tag: yaml:"backup"
	Backup bool `protobuf:"varint,6,opt,name=backup,proto3" json:"backup,omitempty" yaml:"backup"`
	// @inject_tag: yaml:"checksum"
	Checksum string `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty" yaml:"checksum"`
	// @inject_tag: yaml:"decrypt"
	Decrypt *bool `protobuf:"varint,8,opt,name=decrypt,proto3,oneof" json:"decrypt,omitempty" yaml:"decrypt"`
	// @inject_tag: yaml:"directory_mode"
	DirectoryMode string `protobuf:"bytes,9,opt,name=directory_mode,json=directoryMode,proto3" json:"directory_mode,omitempty" yaml:"directory_mode"`
	// @inject_tag: yaml:"follow"
	Follow bool `protobuf:"varint,10,opt,name=follow,proto3" json:"follow,omitempty" yaml:"follow"`
	// @inject_tag: yaml:"force"
	Force *bool `protobuf:"varint,11,opt,name=force,proto3,oneof" json:"force,omitempty" yaml:"force"`
	// @inject_tag: yaml:"group"
	Group string `protobuf:"bytes,12,opt,name=group,proto3" json:"group,omitempty" yaml:"group"`
	// @inject_tag: yaml:"local_follow"
	LocalFollow bool `protobuf:"varint,13,opt,name=local_follow,json=localFollow,proto3" json:"local_follow,omitempty" yaml:"local_follow"`
	// @inject_tag: yaml:"mode"
	Mode string `protobuf:"bytes,14,opt,name=mode,proto3" json:"mode,omitempty" yaml:"mode"`
	// @inject_tag: yaml:"owner"
	Owner string `protobuf:"bytes,15,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	// @inject_tag: yaml:"selevel"
	Selevel string `protobuf:"bytes,16,opt,name=selevel,proto3" json:"selevel,omitempty" yaml:"selevel"`
	// @inject_tag: yaml:"serole"
	Serole string `protobuf:"bytes,17,opt,name=serole,proto3" json:"serole,omitempty" yaml:"serole"`
	// @inject_tag: yaml:"setype"
	Setype string `protobuf:"bytes,18,opt,name=setype,proto3" json:"setype,omitempty" yaml:"setype"`
	// @inject_tag: yaml:"seuser"
	Seuser string `protobuf:"bytes,19,opt,name=seuser,proto3" json:"seuser,omitempty" yaml:"seuser"`
	// @inject_tag: yaml:"unsafe_writes"
	UnsafeWrites bool `protobuf:"varint,20,opt,name=unsafe_writes,json=unsafeWrites,proto3" json:"unsafe_writes,omitempty" yaml:"unsafe_writes"`
	// @inject_tag: yaml:"validate"
	Validate      string `protobuf:"bytes,21,opt,name=validate,proto3" json:"validate,omitempty" yaml:"validate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Copy) Reset() {
	*x = Copy{}
	mi := &file_proto_copy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copy) ProtoMessage() {}

func (x *Copy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_copy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Copy.ProtoReflect.Descriptor instead.
func (*Copy) Descriptor() ([]byte, []int) {
	return file_proto_copy_proto_rawDescGZIP(), []int{0}
}

func (x *Copy) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Copy) GetRemoteSrc() bool {
	if x != nil {
		return x.RemoteSrc
	}
	return false
}

func (x *Copy) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Copy) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Copy) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *Copy) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *Copy) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Copy) GetDecrypt() bool {
	if x != nil && x.Decrypt != nil {
		return *x.Decrypt
	}
	return false
}

func (x *Copy) GetDirectoryMode() string {
	if x != nil {
		return x.DirectoryMode
	}
	return ""
}

func (x *Copy) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *Copy) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *Copy) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Copy) GetLocalFollow() bool {
	if x != nil {
		return x.LocalFollow
	}
	return false
}

func (x *Copy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Copy) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Copy) GetSelevel() string {
	if x != nil {
		return x.Selevel
	}
	return ""
}

func (x *Copy) GetSerole() string {
	if x != nil {
		return x.Serole
	}
	return ""
}

func (x *Copy) GetSetype() string {
	if x != nil {
		return x.Setype
	}
	return ""
}

func (x *Copy) GetSeuser() string {
	if x != nil {
		return x.Seuser
	}
	return ""
}

func (x *Copy) GetUnsafeWrites() bool {
	if x != nil {
		return x.UnsafeWrites
	}
	return false
}

func (x *Copy) GetValidate() string {
	if x != nil {
		return x.Validate
	}
	return ""
}

var File_proto_copy_proto protoreflect.FileDescriptor

const file_proto_copy_proto_rawDesc = "" +
	"\n" +
	"\x10proto/copy.proto\x12\x05proto\"\xce\x04\n" +
	"\x04Copy\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"remote_src\x18\x02 \x01(\bR\tremoteSrc\x12\x10\n" +
	"\x03src\x18\x03 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x04 \x01(\tR\x04dest\x12\x1e\n" +
	"\n" +
	"attributes\x18\x05 \x01(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06backup\x18\x06 \x01(\bR\x06backup\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1d\n" +
	"\adecrypt\x18\b \x01(\bH\x00R\adecrypt\x88\x01\x01\x12%\n" +
	"\x0edirectory_mode\x18\t \x01(\tR\rdirectoryMode\x12\x16\n" +
	"\x06follow\x18\n" +
	" \x01(\bR\x06follow\x12\x19\n" +
	"\x05force\x18\v \x01(\bH\x01R\x05force\x88\x01\x01\x12\x14\n" +
	"\x05group\x18\f \x01(\tR\x05group\x12!\n" +
	"\flocal_follow\x18\r \x01(\bR\vlocalFollow\x12\x12\n" +
	"\x04mode\x18\x0e \x01(\tR\x04mode\x12\x14\n" +
	"\x05owner\x18\x0f \x01(\tR\x05owner\x12\x18\n" +
	"\aselevel\x18\x10 \x01(\tR\aselevel\x12\x16\n" +
	"\x06serole\x18\x11 \x01(\tR\x06serole\x12\x16\n" +
	"\x06setype\x18\x12 \x01(\tR\x06setype\x12\x16\n" +
	"\x06seuser\x18\x13 \x01(\tR\x06seuser\x12#\n" +
	"\runsafe_writes\x18\x14 \x01(\bR\funsafeWrites\x12\x1a\n" +
	"\bvalidate\x18\x15 \x01(\tR\bvalidateB\n" +
	"\n" +
	"\b_decryptB\b\n" +
	"\x06_forceB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_copy_proto_rawDescOnce sync.Once
	file_proto_copy_proto_rawDescData []byte
)

func file_proto_copy_proto_rawDescGZIP() []byte {
	file_proto_copy_proto_rawDescOnce.Do(func() {
		file_proto_copy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_copy_proto_rawDesc), len(file_proto_copy_proto_rawDesc)))
	})
	return file_proto_copy_proto_rawDescData
}

var file_proto_copy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_copy_proto_goTypes = []any{
	(*Copy)(nil), // 0: proto.Copy
}
var file_proto_copy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_copy_proto_init() }
func file_proto_copy_proto_init() {
	if File_proto_copy_proto != nil {
		return
	}
	file_proto_copy_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_copy_proto_rawDesc), len(file_proto_copy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_copy_proto_goTypes,
		DependencyIndexes: file_proto_copy_proto_depIdxs,
		MessageInfos:      file_proto_copy_proto_msgTypes,
	}.Build()
	File_proto_copy_proto = out.File
	file_proto_copy_proto_goTypes = nil
	file_proto_copy_proto_depIdxs = nil
}
