// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/executer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Task  *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	// Variables context (inventory vars, registered vars, etc.)
	Variables *structpb.Struct `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	// Parent path for resolving relative file paths
	// (e.g., roles/rolename for role tasks, playbook dir for play tasks)
	ParentPath string `protobuf:"bytes,3,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"`
	// Whether this task is executing in a role context
	IsRole bool `protobuf:"varint,4,opt,name=is_role,json=isRole,proto3" json:"is_role,omitempty"`
	// Archive containing files needed for task execution
	// (roles/files/, roles/templates/, etc.)
	FileArchive   []byte `protobuf:"bytes,5,opt,name=file_archive,json=fileArchive,proto3" json:"file_archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecuteRequest) Reset() {
	*x = TaskExecuteRequest{}
	mi := &file_proto_executer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecuteRequest) ProtoMessage() {}

func (x *TaskExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecuteRequest.ProtoReflect.Descriptor instead.
func (*TaskExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_executer_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecuteRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskExecuteRequest) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TaskExecuteRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *TaskExecuteRequest) GetIsRole() bool {
	if x != nil {
		return x.IsRole
	}
	return false
}

func (x *TaskExecuteRequest) GetFileArchive() []byte {
	if x != nil {
		return x.FileArchive
	}
	return nil
}

type TaskExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Full task result as JSON map (includes changed, failed, stdout, etc.)
	Result *structpb.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// Error message if execution failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecuteResponse) Reset() {
	*x = TaskExecuteResponse{}
	mi := &file_proto_executer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecuteResponse) ProtoMessage() {}

func (x *TaskExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecuteResponse.ProtoReflect.Descriptor instead.
func (*TaskExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_executer_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskExecuteResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_executer_proto protoreflect.FileDescriptor

const file_proto_executer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executer.proto\x12\x05proto\x1a\x10proto/task.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc9\x01\n" +
	"\x12TaskExecuteRequest\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.proto.TaskR\x04task\x125\n" +
	"\tvariables\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12\x1f\n" +
	"\vparent_path\x18\x03 \x01(\tR\n" +
	"parentPath\x12\x17\n" +
	"\ais_role\x18\x04 \x01(\bR\x06isRole\x12!\n" +
	"\ffile_archive\x18\x05 \x01(\fR\vfileArchive\"v\n" +
	"\x13TaskExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2T\n" +
	"\fTaskExecuter\x12D\n" +
	"\vTaskExecute\x12\x19.proto.TaskExecuteRequest\x1a\x1a.proto.TaskExecuteResponseB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_executer_proto_rawDescOnce sync.Once
	file_proto_executer_proto_rawDescData []byte
)

func file_proto_executer_proto_rawDescGZIP() []byte {
	file_proto_executer_proto_rawDescOnce.Do(func() {
		file_proto_executer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executer_proto_rawDesc), len(file_proto_executer_proto_rawDesc)))
	})
	return file_proto_executer_proto_rawDescData
}

var file_proto_executer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_executer_proto_goTypes = []any{
	(*TaskExecuteRequest)(nil),  // 0: proto.TaskExecuteRequest
	(*TaskExecuteResponse)(nil), // 1: proto.TaskExecuteResponse
	(*Task)(nil),                // 2: proto.Task
	(*structpb.Struct)(nil),     // 3: google.protobuf.Struct
}
var file_proto_executer_proto_depIdxs = []int32{
	2, // 0: proto.TaskExecuteRequest.task:type_name -> proto.Task
	3, // 1: proto.TaskExecuteRequest.variables:type_name -> google.protobuf.Struct
	3, // 2: proto.TaskExecuteResponse.result:type_name -> google.protobuf.Struct
	0, // 3: proto.TaskExecuter.TaskExecute:input_type -> proto.TaskExecuteRequest
	1, // 4: proto.TaskExecuter.TaskExecute:output_type -> proto.TaskExecuteResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_executer_proto_init() }
func file_proto_executer_proto_init() {
	if File_proto_executer_proto != nil {
		return
	}
	file_proto_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executer_proto_rawDesc), len(file_proto_executer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executer_proto_goTypes,
		DependencyIndexes: file_proto_executer_proto_depIdxs,
		MessageInfos:      file_proto_executer_proto_msgTypes,
	}.Build()
	File_proto_executer_proto = out.File
	file_proto_executer_proto_goTypes = nil
	file_proto_executer_proto_depIdxs = nil
}
