// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/executer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExecuter_TaskExecute_FullMethodName = "/proto.TaskExecuter/TaskExecute"
)

// TaskExecuterClient is the client API for TaskExecuter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskExecuterClient interface {
	TaskExecute(ctx context.Context, in *TaskExecuteRequest, opts ...grpc.CallOption) (*TaskExecuteResponse, error)
}

type taskExecuterClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecuterClient(cc grpc.ClientConnInterface) TaskExecuterClient {
	return &taskExecuterClient{cc}
}

func (c *taskExecuterClient) TaskExecute(ctx context.Context, in *TaskExecuteRequest, opts ...grpc.CallOption) (*TaskExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExecuteResponse)
	err := c.cc.Invoke(ctx, TaskExecuter_TaskExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecuterServer is the server API for TaskExecuter service.
// All implementations must embed UnimplementedTaskExecuterServer
// for forward compatibility.
type TaskExecuterServer interface {
	TaskExecute(context.Context, *TaskExecuteRequest) (*TaskExecuteResponse, error)
	mustEmbedUnimplementedTaskExecuterServer()
}

// UnimplementedTaskExecuterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecuterServer struct{}

func (UnimplementedTaskExecuterServer) TaskExecute(context.Context, *TaskExecuteRequest) (*TaskExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskExecute not implemented")
}
func (UnimplementedTaskExecuterServer) mustEmbedUnimplementedTaskExecuterServer() {}
func (UnimplementedTaskExecuterServer) testEmbeddedByValue()                      {}

// UnsafeTaskExecuterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecuterServer will
// result in compilation errors.
type UnsafeTaskExecuterServer interface {
	mustEmbedUnimplementedTaskExecuterServer()
}

func RegisterTaskExecuterServer(s grpc.ServiceRegistrar, srv TaskExecuterServer) {
	// If the following call pancis, it indicates UnimplementedTaskExecuterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecuter_ServiceDesc, srv)
}

func _TaskExecuter_TaskExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecuterServer).TaskExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecuter_TaskExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecuterServer).TaskExecute(ctx, req.(*TaskExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExecuter_ServiceDesc is the grpc.ServiceDesc for TaskExecuter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecuter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TaskExecuter",
	HandlerType: (*TaskExecuterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskExecute",
			Handler:    _TaskExecuter_TaskExecute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/executer.proto",
}
