// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// File manages files and their properties.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"path" sophons:"implemented"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" yaml:"path" sophons:"implemented"`
	// @inject_tag: yaml:"follow" sophons:"implemented"
	Follow *bool `protobuf:"varint,2,opt,name=follow,proto3,oneof" json:"follow,omitempty" yaml:"follow" sophons:"implemented"`
	// @inject_tag: yaml:"group" sophons:"implemented"
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty" yaml:"group" sophons:"implemented"`
	// @inject_tag: yaml:"mode" sophons:"implemented"
	Mode *Mode `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty" yaml:"mode" sophons:"implemented"`
	// @inject_tag: yaml:"owner" sophons:"implemented"
	Owner string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner" sophons:"implemented"`
	// @inject_tag: yaml:"recurse" sophons:"implemented"
	Recurse bool `protobuf:"varint,6,opt,name=recurse,proto3" json:"recurse,omitempty" yaml:"recurse" sophons:"implemented"`
	// @inject_tag: yaml:"src" sophons:"implemented"
	Src string `protobuf:"bytes,7,opt,name=src,proto3" json:"src,omitempty" yaml:"src" sophons:"implemented"`
	// @inject_tag: yaml:"state" sophons:"implemented"
	State string `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty" yaml:"state" sophons:"implemented"`
	// @inject_tag: yaml:"access_time"
	AccessTime string `protobuf:"bytes,9,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty" yaml:"access_time"`
	// @inject_tag: yaml:"access_time_format"
	AccessTimeFormat string `protobuf:"bytes,10,opt,name=access_time_format,json=accessTimeFormat,proto3" json:"access_time_format,omitempty" yaml:"access_time_format"`
	// @inject_tag: yaml:"attributes"
	Attributes string `protobuf:"bytes,11,opt,name=attributes,proto3" json:"attributes,omitempty" yaml:"attributes"`
	// @inject_tag: yaml:"force"
	Force bool `protobuf:"varint,12,opt,name=force,proto3" json:"force,omitempty" yaml:"force"`
	// @inject_tag: yaml:"modification_time"
	ModificationTime string `protobuf:"bytes,13,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty" yaml:"modification_time"`
	// @inject_tag: yaml:"modification_time_format"
	ModificationTimeFormat string `protobuf:"bytes,14,opt,name=modification_time_format,json=modificationTimeFormat,proto3" json:"modification_time_format,omitempty" yaml:"modification_time_format"`
	// @inject_tag: yaml:"selevel"
	Selevel string `protobuf:"bytes,15,opt,name=selevel,proto3" json:"selevel,omitempty" yaml:"selevel"`
	// @inject_tag: yaml:"serole"
	Serole string `protobuf:"bytes,16,opt,name=serole,proto3" json:"serole,omitempty" yaml:"serole"`
	// @inject_tag: yaml:"setype"
	Setype string `protobuf:"bytes,17,opt,name=setype,proto3" json:"setype,omitempty" yaml:"setype"`
	// @inject_tag: yaml:"seuser"
	Seuser string `protobuf:"bytes,18,opt,name=seuser,proto3" json:"seuser,omitempty" yaml:"seuser"`
	// @inject_tag: yaml:"unsafe_writes"
	UnsafeWrites  bool `protobuf:"varint,19,opt,name=unsafe_writes,json=unsafeWrites,proto3" json:"unsafe_writes,omitempty" yaml:"unsafe_writes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetFollow() bool {
	if x != nil && x.Follow != nil {
		return *x.Follow
	}
	return false
}

func (x *File) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *File) GetMode() *Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *File) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *File) GetRecurse() bool {
	if x != nil {
		return x.Recurse
	}
	return false
}

func (x *File) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *File) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *File) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *File) GetAccessTimeFormat() string {
	if x != nil {
		return x.AccessTimeFormat
	}
	return ""
}

func (x *File) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *File) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *File) GetModificationTime() string {
	if x != nil {
		return x.ModificationTime
	}
	return ""
}

func (x *File) GetModificationTimeFormat() string {
	if x != nil {
		return x.ModificationTimeFormat
	}
	return ""
}

func (x *File) GetSelevel() string {
	if x != nil {
		return x.Selevel
	}
	return ""
}

func (x *File) GetSerole() string {
	if x != nil {
		return x.Serole
	}
	return ""
}

func (x *File) GetSetype() string {
	if x != nil {
		return x.Setype
	}
	return ""
}

func (x *File) GetSeuser() string {
	if x != nil {
		return x.Seuser
	}
	return ""
}

func (x *File) GetUnsafeWrites() bool {
	if x != nil {
		return x.UnsafeWrites
	}
	return false
}

var File_proto_file_proto protoreflect.FileDescriptor

const file_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x10proto/file.proto\x12\x05proto\x1a\x10proto/mode.proto\"\xc4\x04\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\x06follow\x18\x02 \x01(\bH\x00R\x06follow\x88\x01\x01\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x1f\n" +
	"\x04mode\x18\x04 \x01(\v2\v.proto.ModeR\x04mode\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x18\n" +
	"\arecurse\x18\x06 \x01(\bR\arecurse\x12\x10\n" +
	"\x03src\x18\a \x01(\tR\x03src\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x1f\n" +
	"\vaccess_time\x18\t \x01(\tR\n" +
	"accessTime\x12,\n" +
	"\x12access_time_format\x18\n" +
	" \x01(\tR\x10accessTimeFormat\x12\x1e\n" +
	"\n" +
	"attributes\x18\v \x01(\tR\n" +
	"attributes\x12\x14\n" +
	"\x05force\x18\f \x01(\bR\x05force\x12+\n" +
	"\x11modification_time\x18\r \x01(\tR\x10modificationTime\x128\n" +
	"\x18modification_time_format\x18\x0e \x01(\tR\x16modificationTimeFormat\x12\x18\n" +
	"\aselevel\x18\x0f \x01(\tR\aselevel\x12\x16\n" +
	"\x06serole\x18\x10 \x01(\tR\x06serole\x12\x16\n" +
	"\x06setype\x18\x11 \x01(\tR\x06setype\x12\x16\n" +
	"\x06seuser\x18\x12 \x01(\tR\x06seuser\x12#\n" +
	"\runsafe_writes\x18\x13 \x01(\bR\funsafeWritesB\t\n" +
	"\a_followB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_file_proto_rawDescOnce sync.Once
	file_proto_file_proto_rawDescData []byte
)

func file_proto_file_proto_rawDescGZIP() []byte {
	file_proto_file_proto_rawDescOnce.Do(func() {
		file_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)))
	})
	return file_proto_file_proto_rawDescData
}

var file_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_file_proto_goTypes = []any{
	(*File)(nil), // 0: proto.File
	(*Mode)(nil), // 1: proto.Mode
}
var file_proto_file_proto_depIdxs = []int32{
	1, // 0: proto.File.mode:type_name -> proto.Mode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_file_proto_init() }
func file_proto_file_proto_init() {
	if File_proto_file_proto != nil {
		return
	}
	file_proto_mode_proto_init()
	file_proto_file_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_proto_rawDesc), len(file_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_file_proto_goTypes,
		DependencyIndexes: file_proto_file_proto_depIdxs,
		MessageInfos:      file_proto_file_proto_msgTypes,
	}.Build()
	File_proto_file_proto = out.File
	file_proto_file_proto_goTypes = nil
	file_proto_file_proto_depIdxs = nil
}
