// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/get_url.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetURL downloads files from HTTP, HTTPS, or FTP on the target host.
type GetURL struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"dest" sophons:"implemented"
	Dest string `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty" yaml:"dest" sophons:"implemented"`
	// @inject_tag: yaml:"url" sophons:"implemented"
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty" yaml:"url" sophons:"implemented"`
	// @inject_tag: yaml:"group" sophons:"implemented"
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty" yaml:"group" sophons:"implemented"`
	// @inject_tag: yaml:"mode" sophons:"implemented"
	Mode *Mode `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty" yaml:"mode" sophons:"implemented"`
	// @inject_tag: yaml:"owner" sophons:"implemented"
	Owner string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner" sophons:"implemented"`
	// @inject_tag: yaml:"attributes"
	Attributes string `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty" yaml:"attributes"`
	// @inject_tag: yaml:"backup"
	Backup bool `protobuf:"varint,7,opt,name=backup,proto3" json:"backup,omitempty" yaml:"backup"`
	// @inject_tag: yaml:"checksum"
	Checksum string `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty" yaml:"checksum"`
	// @inject_tag: yaml:"ciphers"
	Ciphers []string `protobuf:"bytes,9,rep,name=ciphers,proto3" json:"ciphers,omitempty" yaml:"ciphers"`
	// @inject_tag: yaml:"client_cert"
	ClientCert string `protobuf:"bytes,10,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty" yaml:"client_cert"`
	// @inject_tag: yaml:"client_key"
	ClientKey string `protobuf:"bytes,11,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty" yaml:"client_key"`
	// @inject_tag: yaml:"decompress"
	Decompress *bool `protobuf:"varint,12,opt,name=decompress,proto3,oneof" json:"decompress,omitempty" yaml:"decompress"`
	// @inject_tag: yaml:"force"
	Force *bool `protobuf:"varint,13,opt,name=force,proto3,oneof" json:"force,omitempty" yaml:"force"`
	// @inject_tag: yaml:"force_basic_auth"
	ForceBasicAuth bool `protobuf:"varint,14,opt,name=force_basic_auth,json=forceBasicAuth,proto3" json:"force_basic_auth,omitempty" yaml:"force_basic_auth"`
	// @inject_tag: yaml:"headers"
	Headers map[string]string `protobuf:"bytes,15,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" yaml:"headers"`
	// @inject_tag: yaml:"selevel"
	Selevel string `protobuf:"bytes,16,opt,name=selevel,proto3" json:"selevel,omitempty" yaml:"selevel"`
	// @inject_tag: yaml:"serole"
	Serole string `protobuf:"bytes,17,opt,name=serole,proto3" json:"serole,omitempty" yaml:"serole"`
	// @inject_tag: yaml:"setype"
	Setype string `protobuf:"bytes,18,opt,name=setype,proto3" json:"setype,omitempty" yaml:"setype"`
	// @inject_tag: yaml:"seuser"
	Seuser string `protobuf:"bytes,19,opt,name=seuser,proto3" json:"seuser,omitempty" yaml:"seuser"`
	// @inject_tag: yaml:"timeout"
	Timeout uint64 `protobuf:"varint,20,opt,name=timeout,proto3" json:"timeout,omitempty" yaml:"timeout"`
	// @inject_tag: yaml:"tmp_dest"
	TmpDest string `protobuf:"bytes,21,opt,name=tmp_dest,json=tmpDest,proto3" json:"tmp_dest,omitempty" yaml:"tmp_dest"`
	// @inject_tag: yaml:"unredirected_headers"
	UnredirectedHeaders []string `protobuf:"bytes,22,rep,name=unredirected_headers,json=unredirectedHeaders,proto3" json:"unredirected_headers,omitempty" yaml:"unredirected_headers"`
	// @inject_tag: yaml:"unsafe_writes"
	UnsafeWrites bool `protobuf:"varint,23,opt,name=unsafe_writes,json=unsafeWrites,proto3" json:"unsafe_writes,omitempty" yaml:"unsafe_writes"`
	// @inject_tag: yaml:"url_password"
	UrlPassword string `protobuf:"bytes,24,opt,name=url_password,json=urlPassword,proto3" json:"url_password,omitempty" yaml:"url_password"`
	// @inject_tag: yaml:"url_username"
	UrlUsername string `protobuf:"bytes,25,opt,name=url_username,json=urlUsername,proto3" json:"url_username,omitempty" yaml:"url_username"`
	// @inject_tag: yaml:"use_gssapi"
	UseGssapi bool `protobuf:"varint,26,opt,name=use_gssapi,json=useGssapi,proto3" json:"use_gssapi,omitempty" yaml:"use_gssapi"`
	// @inject_tag: yaml:"use_netrc"
	UseNetrc *bool `protobuf:"varint,27,opt,name=use_netrc,json=useNetrc,proto3,oneof" json:"use_netrc,omitempty" yaml:"use_netrc"`
	// @inject_tag: yaml:"use_proxy"
	UseProxy *bool `protobuf:"varint,28,opt,name=use_proxy,json=useProxy,proto3,oneof" json:"use_proxy,omitempty" yaml:"use_proxy"`
	// @inject_tag: yaml:"validate_certs"
	ValidateCerts *bool `protobuf:"varint,29,opt,name=validate_certs,json=validateCerts,proto3,oneof" json:"validate_certs,omitempty" yaml:"validate_certs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURL) Reset() {
	*x = GetURL{}
	mi := &file_proto_get_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURL) ProtoMessage() {}

func (x *GetURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_get_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURL.ProtoReflect.Descriptor instead.
func (*GetURL) Descriptor() ([]byte, []int) {
	return file_proto_get_url_proto_rawDescGZIP(), []int{0}
}

func (x *GetURL) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *GetURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetURL) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetURL) GetMode() *Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *GetURL) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetURL) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *GetURL) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *GetURL) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *GetURL) GetCiphers() []string {
	if x != nil {
		return x.Ciphers
	}
	return nil
}

func (x *GetURL) GetClientCert() string {
	if x != nil {
		return x.ClientCert
	}
	return ""
}

func (x *GetURL) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *GetURL) GetDecompress() bool {
	if x != nil && x.Decompress != nil {
		return *x.Decompress
	}
	return false
}

func (x *GetURL) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *GetURL) GetForceBasicAuth() bool {
	if x != nil {
		return x.ForceBasicAuth
	}
	return false
}

func (x *GetURL) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GetURL) GetSelevel() string {
	if x != nil {
		return x.Selevel
	}
	return ""
}

func (x *GetURL) GetSerole() string {
	if x != nil {
		return x.Serole
	}
	return ""
}

func (x *GetURL) GetSetype() string {
	if x != nil {
		return x.Setype
	}
	return ""
}

func (x *GetURL) GetSeuser() string {
	if x != nil {
		return x.Seuser
	}
	return ""
}

func (x *GetURL) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GetURL) GetTmpDest() string {
	if x != nil {
		return x.TmpDest
	}
	return ""
}

func (x *GetURL) GetUnredirectedHeaders() []string {
	if x != nil {
		return x.UnredirectedHeaders
	}
	return nil
}

func (x *GetURL) GetUnsafeWrites() bool {
	if x != nil {
		return x.UnsafeWrites
	}
	return false
}

func (x *GetURL) GetUrlPassword() string {
	if x != nil {
		return x.UrlPassword
	}
	return ""
}

func (x *GetURL) GetUrlUsername() string {
	if x != nil {
		return x.UrlUsername
	}
	return ""
}

func (x *GetURL) GetUseGssapi() bool {
	if x != nil {
		return x.UseGssapi
	}
	return false
}

func (x *GetURL) GetUseNetrc() bool {
	if x != nil && x.UseNetrc != nil {
		return *x.UseNetrc
	}
	return false
}

func (x *GetURL) GetUseProxy() bool {
	if x != nil && x.UseProxy != nil {
		return *x.UseProxy
	}
	return false
}

func (x *GetURL) GetValidateCerts() bool {
	if x != nil && x.ValidateCerts != nil {
		return *x.ValidateCerts
	}
	return false
}

var File_proto_get_url_proto protoreflect.FileDescriptor

const file_proto_get_url_proto_rawDesc = "" +
	"\n" +
	"\x13proto/get_url.proto\x12\x05proto\x1a\x10proto/mode.proto\"\x91\b\n" +
	"\x06GetURL\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x1f\n" +
	"\x04mode\x18\x04 \x01(\v2\v.proto.ModeR\x04mode\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x1e\n" +
	"\n" +
	"attributes\x18\x06 \x01(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06backup\x18\a \x01(\bR\x06backup\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\tR\bchecksum\x12\x18\n" +
	"\aciphers\x18\t \x03(\tR\aciphers\x12\x1f\n" +
	"\vclient_cert\x18\n" +
	" \x01(\tR\n" +
	"clientCert\x12\x1d\n" +
	"\n" +
	"client_key\x18\v \x01(\tR\tclientKey\x12#\n" +
	"\n" +
	"decompress\x18\f \x01(\bH\x00R\n" +
	"decompress\x88\x01\x01\x12\x19\n" +
	"\x05force\x18\r \x01(\bH\x01R\x05force\x88\x01\x01\x12(\n" +
	"\x10force_basic_auth\x18\x0e \x01(\bR\x0eforceBasicAuth\x124\n" +
	"\aheaders\x18\x0f \x03(\v2\x1a.proto.GetURL.HeadersEntryR\aheaders\x12\x18\n" +
	"\aselevel\x18\x10 \x01(\tR\aselevel\x12\x16\n" +
	"\x06serole\x18\x11 \x01(\tR\x06serole\x12\x16\n" +
	"\x06setype\x18\x12 \x01(\tR\x06setype\x12\x16\n" +
	"\x06seuser\x18\x13 \x01(\tR\x06seuser\x12\x18\n" +
	"\atimeout\x18\x14 \x01(\x04R\atimeout\x12\x19\n" +
	"\btmp_dest\x18\x15 \x01(\tR\atmpDest\x121\n" +
	"\x14unredirected_headers\x18\x16 \x03(\tR\x13unredirectedHeaders\x12#\n" +
	"\runsafe_writes\x18\x17 \x01(\bR\funsafeWrites\x12!\n" +
	"\furl_password\x18\x18 \x01(\tR\vurlPassword\x12!\n" +
	"\furl_username\x18\x19 \x01(\tR\vurlUsername\x12\x1d\n" +
	"\n" +
	"use_gssapi\x18\x1a \x01(\bR\tuseGssapi\x12 \n" +
	"\tuse_netrc\x18\x1b \x01(\bH\x02R\buseNetrc\x88\x01\x01\x12 \n" +
	"\tuse_proxy\x18\x1c \x01(\bH\x03R\buseProxy\x88\x01\x01\x12*\n" +
	"\x0evalidate_certs\x18\x1d \x01(\bH\x04R\rvalidateCerts\x88\x01\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_decompressB\b\n" +
	"\x06_forceB\f\n" +
	"\n" +
	"_use_netrcB\f\n" +
	"\n" +
	"_use_proxyB\x11\n" +
	"\x0f_validate_certsB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_get_url_proto_rawDescOnce sync.Once
	file_proto_get_url_proto_rawDescData []byte
)

func file_proto_get_url_proto_rawDescGZIP() []byte {
	file_proto_get_url_proto_rawDescOnce.Do(func() {
		file_proto_get_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_get_url_proto_rawDesc), len(file_proto_get_url_proto_rawDesc)))
	})
	return file_proto_get_url_proto_rawDescData
}

var file_proto_get_url_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_get_url_proto_goTypes = []any{
	(*GetURL)(nil), // 0: proto.GetURL
	nil,            // 1: proto.GetURL.HeadersEntry
	(*Mode)(nil),   // 2: proto.Mode
}
var file_proto_get_url_proto_depIdxs = []int32{
	2, // 0: proto.GetURL.mode:type_name -> proto.Mode
	1, // 1: proto.GetURL.headers:type_name -> proto.GetURL.HeadersEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_get_url_proto_init() }
func file_proto_get_url_proto_init() {
	if File_proto_get_url_proto != nil {
		return
	}
	file_proto_mode_proto_init()
	file_proto_get_url_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_get_url_proto_rawDesc), len(file_proto_get_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_get_url_proto_goTypes,
		DependencyIndexes: file_proto_get_url_proto_depIdxs,
		MessageInfos:      file_proto_get_url_proto_msgTypes,
	}.Build()
	File_proto_get_url_proto = out.File
	file_proto_get_url_proto_goTypes = nil
	file_proto_get_url_proto_depIdxs = nil
}
