// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/include_tasks.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncludeTasks includes a file with a list of tasks.
type IncludeTasks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"apply"
	ApplyKeywords *structpb.Struct `protobuf:"bytes,1,opt,name=apply_keywords,json=applyKeywords,proto3" json:"apply_keywords,omitempty" yaml:"apply"`
	// @inject_tag: yaml:"file" sophons:"implemented"
	File          string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty" yaml:"file" sophons:"implemented"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncludeTasks) Reset() {
	*x = IncludeTasks{}
	mi := &file_proto_include_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludeTasks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludeTasks) ProtoMessage() {}

func (x *IncludeTasks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_include_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludeTasks.ProtoReflect.Descriptor instead.
func (*IncludeTasks) Descriptor() ([]byte, []int) {
	return file_proto_include_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *IncludeTasks) GetApplyKeywords() *structpb.Struct {
	if x != nil {
		return x.ApplyKeywords
	}
	return nil
}

func (x *IncludeTasks) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_proto_include_tasks_proto protoreflect.FileDescriptor

const file_proto_include_tasks_proto_rawDesc = "" +
	"\n" +
	"\x19proto/include_tasks.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\"b\n" +
	"\fIncludeTasks\x12>\n" +
	"\x0eapply_keywords\x18\x01 \x01(\v2\x17.google.protobuf.StructR\rapplyKeywords\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04fileB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_include_tasks_proto_rawDescOnce sync.Once
	file_proto_include_tasks_proto_rawDescData []byte
)

func file_proto_include_tasks_proto_rawDescGZIP() []byte {
	file_proto_include_tasks_proto_rawDescOnce.Do(func() {
		file_proto_include_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_include_tasks_proto_rawDesc), len(file_proto_include_tasks_proto_rawDesc)))
	})
	return file_proto_include_tasks_proto_rawDescData
}

var file_proto_include_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_include_tasks_proto_goTypes = []any{
	(*IncludeTasks)(nil),    // 0: proto.IncludeTasks
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_proto_include_tasks_proto_depIdxs = []int32{
	1, // 0: proto.IncludeTasks.apply_keywords:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_include_tasks_proto_init() }
func file_proto_include_tasks_proto_init() {
	if File_proto_include_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_include_tasks_proto_rawDesc), len(file_proto_include_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_include_tasks_proto_goTypes,
		DependencyIndexes: file_proto_include_tasks_proto_depIdxs,
		MessageInfos:      file_proto_include_tasks_proto_msgTypes,
	}.Build()
	File_proto_include_tasks_proto = out.File
	file_proto_include_tasks_proto_goTypes = nil
	file_proto_include_tasks_proto_depIdxs = nil
}
