// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/mode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode represents file permissions, supporting both string and numeric formats.
type Mode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"value"
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_proto_mode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_proto_mode_proto_rawDescGZIP(), []int{0}
}

func (x *Mode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_mode_proto protoreflect.FileDescriptor

const file_proto_mode_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mode.proto\x12\x05proto\"\x1c\n" +
	"\x04Mode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_mode_proto_rawDescOnce sync.Once
	file_proto_mode_proto_rawDescData []byte
)

func file_proto_mode_proto_rawDescGZIP() []byte {
	file_proto_mode_proto_rawDescOnce.Do(func() {
		file_proto_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mode_proto_rawDesc), len(file_proto_mode_proto_rawDesc)))
	})
	return file_proto_mode_proto_rawDescData
}

var file_proto_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_mode_proto_goTypes = []any{
	(*Mode)(nil), // 0: proto.Mode
}
var file_proto_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mode_proto_init() }
func file_proto_mode_proto_init() {
	if File_proto_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mode_proto_rawDesc), len(file_proto_mode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mode_proto_goTypes,
		DependencyIndexes: file_proto_mode_proto_depIdxs,
		MessageInfos:      file_proto_mode_proto_msgTypes,
	}.Build()
	File_proto_mode_proto = out.File
	file_proto_mode_proto_goTypes = nil
	file_proto_mode_proto_depIdxs = nil
}
