// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/shell.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shell executes a command in a shell on the target host.
type Shell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"argv" sophons:"implemented"
	Argv []string `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty" yaml:"argv" sophons:"implemented"`
	// @inject_tag: yaml:"chdir" sophons:"implemented"
	Chdir string `protobuf:"bytes,2,opt,name=chdir,proto3" json:"chdir,omitempty" yaml:"chdir" sophons:"implemented"`
	// @inject_tag: yaml:"cmd" sophons:"implemented"
	Cmd string `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty" yaml:"cmd" sophons:"implemented"`
	// @inject_tag: yaml:"creates" sophons:"implemented"
	Creates string `protobuf:"bytes,4,opt,name=creates,proto3" json:"creates,omitempty" yaml:"creates" sophons:"implemented"`
	// @inject_tag: yaml:"executable" sophons:"implemented"
	Executable string `protobuf:"bytes,5,opt,name=executable,proto3" json:"executable,omitempty" yaml:"executable" sophons:"implemented"`
	// @inject_tag: yaml:"removes" sophons:"implemented"
	Removes string `protobuf:"bytes,6,opt,name=removes,proto3" json:"removes,omitempty" yaml:"removes" sophons:"implemented"`
	// @inject_tag: yaml:"stdin" sophons:"implemented"
	Stdin string `protobuf:"bytes,7,opt,name=stdin,proto3" json:"stdin,omitempty" yaml:"stdin" sophons:"implemented"`
	// @inject_tag: yaml:"stdin_add_newline" sophons:"implemented"
	StdinAddNewline *bool `protobuf:"varint,8,opt,name=stdin_add_newline,json=stdinAddNewline,proto3,oneof" json:"stdin_add_newline,omitempty" yaml:"stdin_add_newline" sophons:"implemented"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Shell) Reset() {
	*x = Shell{}
	mi := &file_proto_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shell) ProtoMessage() {}

func (x *Shell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shell.ProtoReflect.Descriptor instead.
func (*Shell) Descriptor() ([]byte, []int) {
	return file_proto_shell_proto_rawDescGZIP(), []int{0}
}

func (x *Shell) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *Shell) GetChdir() string {
	if x != nil {
		return x.Chdir
	}
	return ""
}

func (x *Shell) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Shell) GetCreates() string {
	if x != nil {
		return x.Creates
	}
	return ""
}

func (x *Shell) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *Shell) GetRemoves() string {
	if x != nil {
		return x.Removes
	}
	return ""
}

func (x *Shell) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *Shell) GetStdinAddNewline() bool {
	if x != nil && x.StdinAddNewline != nil {
		return *x.StdinAddNewline
	}
	return false
}

var File_proto_shell_proto protoreflect.FileDescriptor

const file_proto_shell_proto_rawDesc = "" +
	"\n" +
	"\x11proto/shell.proto\x12\x05proto\"\xf4\x01\n" +
	"\x05Shell\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12\x14\n" +
	"\x05chdir\x18\x02 \x01(\tR\x05chdir\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x12\x18\n" +
	"\acreates\x18\x04 \x01(\tR\acreates\x12\x1e\n" +
	"\n" +
	"executable\x18\x05 \x01(\tR\n" +
	"executable\x12\x18\n" +
	"\aremoves\x18\x06 \x01(\tR\aremoves\x12\x14\n" +
	"\x05stdin\x18\a \x01(\tR\x05stdin\x12/\n" +
	"\x11stdin_add_newline\x18\b \x01(\bH\x00R\x0fstdinAddNewline\x88\x01\x01B\x14\n" +
	"\x12_stdin_add_newlineB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_shell_proto_rawDescOnce sync.Once
	file_proto_shell_proto_rawDescData []byte
)

func file_proto_shell_proto_rawDescGZIP() []byte {
	file_proto_shell_proto_rawDescOnce.Do(func() {
		file_proto_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shell_proto_rawDesc), len(file_proto_shell_proto_rawDesc)))
	})
	return file_proto_shell_proto_rawDescData
}

var file_proto_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_shell_proto_goTypes = []any{
	(*Shell)(nil), // 0: proto.Shell
}
var file_proto_shell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shell_proto_init() }
func file_proto_shell_proto_init() {
	if File_proto_shell_proto != nil {
		return
	}
	file_proto_shell_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shell_proto_rawDesc), len(file_proto_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_shell_proto_goTypes,
		DependencyIndexes: file_proto_shell_proto_depIdxs,
		MessageInfos:      file_proto_shell_proto_msgTypes,
	}.Build()
	File_proto_shell_proto = out.File
	file_proto_shell_proto_goTypes = nil
	file_proto_shell_proto_depIdxs = nil
}
