// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task is a single task to be executed.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	// @inject_tag: yaml:"when"
	When string `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty" yaml:"when"`
	// Loop can be a string (Jinja template), array of strings, or array of objects
	// @inject_tag: yaml:"loop"
	Loop *structpb.Value `protobuf:"bytes,3,opt,name=loop,proto3" json:"loop,omitempty" yaml:"loop"`
	// @inject_tag: yaml:"register"
	Register string `protobuf:"bytes,4,opt,name=register,proto3" json:"register,omitempty" yaml:"register"`
	// Types that are valid to be assigned to Content:
	//
	//	*Task_Apt
	//	*Task_AptRepository
	//	*Task_Command
	//	*Task_Copy
	//	*Task_File
	//	*Task_GetUrl
	//	*Task_ImportTasks
	//	*Task_IncludeTasks
	//	*Task_Shell
	//	*Task_Template
	Content       isTask_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *Task) GetLoop() *structpb.Value {
	if x != nil {
		return x.Loop
	}
	return nil
}

func (x *Task) GetRegister() string {
	if x != nil {
		return x.Register
	}
	return ""
}

func (x *Task) GetContent() isTask_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Task) GetApt() *Apt {
	if x != nil {
		if x, ok := x.Content.(*Task_Apt); ok {
			return x.Apt
		}
	}
	return nil
}

func (x *Task) GetAptRepository() *AptRepository {
	if x != nil {
		if x, ok := x.Content.(*Task_AptRepository); ok {
			return x.AptRepository
		}
	}
	return nil
}

func (x *Task) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Content.(*Task_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Task) GetCopy() *Copy {
	if x != nil {
		if x, ok := x.Content.(*Task_Copy); ok {
			return x.Copy
		}
	}
	return nil
}

func (x *Task) GetFile() *File {
	if x != nil {
		if x, ok := x.Content.(*Task_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Task) GetGetUrl() *GetURL {
	if x != nil {
		if x, ok := x.Content.(*Task_GetUrl); ok {
			return x.GetUrl
		}
	}
	return nil
}

func (x *Task) GetImportTasks() *ImportTasks {
	if x != nil {
		if x, ok := x.Content.(*Task_ImportTasks); ok {
			return x.ImportTasks
		}
	}
	return nil
}

func (x *Task) GetIncludeTasks() *IncludeTasks {
	if x != nil {
		if x, ok := x.Content.(*Task_IncludeTasks); ok {
			return x.IncludeTasks
		}
	}
	return nil
}

func (x *Task) GetShell() *Shell {
	if x != nil {
		if x, ok := x.Content.(*Task_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

func (x *Task) GetTemplate() *Template {
	if x != nil {
		if x, ok := x.Content.(*Task_Template); ok {
			return x.Template
		}
	}
	return nil
}

type isTask_Content interface {
	isTask_Content()
}

type Task_Apt struct {
	Apt *Apt `protobuf:"bytes,5,opt,name=apt,proto3,oneof"`
}

type Task_AptRepository struct {
	AptRepository *AptRepository `protobuf:"bytes,6,opt,name=apt_repository,json=aptRepository,proto3,oneof"`
}

type Task_Command struct {
	Command *Command `protobuf:"bytes,7,opt,name=command,proto3,oneof"`
}

type Task_Copy struct {
	Copy *Copy `protobuf:"bytes,8,opt,name=copy,proto3,oneof"`
}

type Task_File struct {
	File *File `protobuf:"bytes,9,opt,name=file,proto3,oneof"`
}

type Task_GetUrl struct {
	GetUrl *GetURL `protobuf:"bytes,10,opt,name=get_url,json=getUrl,proto3,oneof"`
}

type Task_ImportTasks struct {
	ImportTasks *ImportTasks `protobuf:"bytes,11,opt,name=import_tasks,json=importTasks,proto3,oneof"`
}

type Task_IncludeTasks struct {
	IncludeTasks *IncludeTasks `protobuf:"bytes,12,opt,name=include_tasks,json=includeTasks,proto3,oneof"`
}

type Task_Shell struct {
	Shell *Shell `protobuf:"bytes,13,opt,name=shell,proto3,oneof"`
}

type Task_Template struct {
	Template *Template `protobuf:"bytes,14,opt,name=template,proto3,oneof"`
}

func (*Task_Apt) isTask_Content() {}

func (*Task_AptRepository) isTask_Content() {}

func (*Task_Command) isTask_Content() {}

func (*Task_Copy) isTask_Content() {}

func (*Task_File) isTask_Content() {}

func (*Task_GetUrl) isTask_Content() {}

func (*Task_ImportTasks) isTask_Content() {}

func (*Task_IncludeTasks) isTask_Content() {}

func (*Task_Shell) isTask_Content() {}

func (*Task_Template) isTask_Content() {}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fproto/apt.proto\x1a\x1aproto/apt_repository.proto\x1a\x13proto/command.proto\x1a\x10proto/copy.proto\x1a\x10proto/file.proto\x1a\x13proto/get_url.proto\x1a\x18proto/import_tasks.proto\x1a\x19proto/include_tasks.proto\x1a\x11proto/shell.proto\x1a\x14proto/template.proto\"\xc6\x04\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04when\x18\x02 \x01(\tR\x04when\x12*\n" +
	"\x04loop\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04loop\x12\x1a\n" +
	"\bregister\x18\x04 \x01(\tR\bregister\x12\x1e\n" +
	"\x03apt\x18\x05 \x01(\v2\n" +
	".proto.AptH\x00R\x03apt\x12=\n" +
	"\x0eapt_repository\x18\x06 \x01(\v2\x14.proto.AptRepositoryH\x00R\raptRepository\x12*\n" +
	"\acommand\x18\a \x01(\v2\x0e.proto.CommandH\x00R\acommand\x12!\n" +
	"\x04copy\x18\b \x01(\v2\v.proto.CopyH\x00R\x04copy\x12!\n" +
	"\x04file\x18\t \x01(\v2\v.proto.FileH\x00R\x04file\x12(\n" +
	"\aget_url\x18\n" +
	" \x01(\v2\r.proto.GetURLH\x00R\x06getUrl\x127\n" +
	"\fimport_tasks\x18\v \x01(\v2\x12.proto.ImportTasksH\x00R\vimportTasks\x12:\n" +
	"\rinclude_tasks\x18\f \x01(\v2\x13.proto.IncludeTasksH\x00R\fincludeTasks\x12$\n" +
	"\x05shell\x18\r \x01(\v2\f.proto.ShellH\x00R\x05shell\x12-\n" +
	"\btemplate\x18\x0e \x01(\v2\x0f.proto.TemplateH\x00R\btemplateB\t\n" +
	"\acontentB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_task_proto_goTypes = []any{
	(*Task)(nil),           // 0: proto.Task
	(*structpb.Value)(nil), // 1: google.protobuf.Value
	(*Apt)(nil),            // 2: proto.Apt
	(*AptRepository)(nil),  // 3: proto.AptRepository
	(*Command)(nil),        // 4: proto.Command
	(*Copy)(nil),           // 5: proto.Copy
	(*File)(nil),           // 6: proto.File
	(*GetURL)(nil),         // 7: proto.GetURL
	(*ImportTasks)(nil),    // 8: proto.ImportTasks
	(*IncludeTasks)(nil),   // 9: proto.IncludeTasks
	(*Shell)(nil),          // 10: proto.Shell
	(*Template)(nil),       // 11: proto.Template
}
var file_proto_task_proto_depIdxs = []int32{
	1,  // 0: proto.Task.loop:type_name -> google.protobuf.Value
	2,  // 1: proto.Task.apt:type_name -> proto.Apt
	3,  // 2: proto.Task.apt_repository:type_name -> proto.AptRepository
	4,  // 3: proto.Task.command:type_name -> proto.Command
	5,  // 4: proto.Task.copy:type_name -> proto.Copy
	6,  // 5: proto.Task.file:type_name -> proto.File
	7,  // 6: proto.Task.get_url:type_name -> proto.GetURL
	8,  // 7: proto.Task.import_tasks:type_name -> proto.ImportTasks
	9,  // 8: proto.Task.include_tasks:type_name -> proto.IncludeTasks
	10, // 9: proto.Task.shell:type_name -> proto.Shell
	11, // 10: proto.Task.template:type_name -> proto.Template
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	file_proto_apt_proto_init()
	file_proto_apt_repository_proto_init()
	file_proto_command_proto_init()
	file_proto_copy_proto_init()
	file_proto_file_proto_init()
	file_proto_get_url_proto_init()
	file_proto_import_tasks_proto_init()
	file_proto_include_tasks_proto_init()
	file_proto_shell_proto_init()
	file_proto_template_proto_init()
	file_proto_task_proto_msgTypes[0].OneofWrappers = []any{
		(*Task_Apt)(nil),
		(*Task_AptRepository)(nil),
		(*Task_Command)(nil),
		(*Task_Copy)(nil),
		(*Task_File)(nil),
		(*Task_GetUrl)(nil),
		(*Task_ImportTasks)(nil),
		(*Task_IncludeTasks)(nil),
		(*Task_Shell)(nil),
		(*Task_Template)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
