// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/template.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Template copies a file from the controller to the target host and substitutes variables in it.
type Template struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"dest" sophons:"implemented"
	Dest string `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty" yaml:"dest" sophons:"implemented"`
	// @inject_tag: yaml:"group" sophons:"implemented"
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty" yaml:"group" sophons:"implemented"`
	// @inject_tag: yaml:"mode" sophons:"implemented"
	Mode *Mode `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty" yaml:"mode" sophons:"implemented"`
	// @inject_tag: yaml:"owner" sophons:"implemented"
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner" sophons:"implemented"`
	// @inject_tag: yaml:"src" sophons:"implemented"
	Src string `protobuf:"bytes,5,opt,name=src,proto3" json:"src,omitempty" yaml:"src" sophons:"implemented"`
	// @inject_tag: yaml:"attributes"
	Attributes string `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty" yaml:"attributes"`
	// @inject_tag: yaml:"backup"
	Backup bool `protobuf:"varint,7,opt,name=backup,proto3" json:"backup,omitempty" yaml:"backup"`
	// @inject_tag: yaml:"block_end_string"
	BlockEndString string `protobuf:"bytes,8,opt,name=block_end_string,json=blockEndString,proto3" json:"block_end_string,omitempty" yaml:"block_end_string"`
	// @inject_tag: yaml:"block_start_string"
	BlockStartString string `protobuf:"bytes,9,opt,name=block_start_string,json=blockStartString,proto3" json:"block_start_string,omitempty" yaml:"block_start_string"`
	// @inject_tag: yaml:"comment_end_string"
	CommentEndString string `protobuf:"bytes,10,opt,name=comment_end_string,json=commentEndString,proto3" json:"comment_end_string,omitempty" yaml:"comment_end_string"`
	// @inject_tag: yaml:"comment_start_string"
	CommentStartString string `protobuf:"bytes,11,opt,name=comment_start_string,json=commentStartString,proto3" json:"comment_start_string,omitempty" yaml:"comment_start_string"`
	// @inject_tag: yaml:"follow"
	Follow bool `protobuf:"varint,12,opt,name=follow,proto3" json:"follow,omitempty" yaml:"follow"`
	// @inject_tag: yaml:"force"
	Force *bool `protobuf:"varint,13,opt,name=force,proto3,oneof" json:"force,omitempty" yaml:"force"`
	// @inject_tag: yaml:"lstrip_blocks"
	LstripBlocks bool `protobuf:"varint,14,opt,name=lstrip_blocks,json=lstripBlocks,proto3" json:"lstrip_blocks,omitempty" yaml:"lstrip_blocks"`
	// @inject_tag: yaml:"newline_sequence"
	NewlineSequence string `protobuf:"bytes,15,opt,name=newline_sequence,json=newlineSequence,proto3" json:"newline_sequence,omitempty" yaml:"newline_sequence"`
	// @inject_tag: yaml:"output_encoding"
	OutputEncoding string `protobuf:"bytes,16,opt,name=output_encoding,json=outputEncoding,proto3" json:"output_encoding,omitempty" yaml:"output_encoding"`
	// @inject_tag: yaml:"selevel"
	Selevel string `protobuf:"bytes,17,opt,name=selevel,proto3" json:"selevel,omitempty" yaml:"selevel"`
	// @inject_tag: yaml:"serole"
	Serole string `protobuf:"bytes,18,opt,name=serole,proto3" json:"serole,omitempty" yaml:"serole"`
	// @inject_tag: yaml:"setype"
	Setype string `protobuf:"bytes,19,opt,name=setype,proto3" json:"setype,omitempty" yaml:"setype"`
	// @inject_tag: yaml:"seuser"
	Seuser string `protobuf:"bytes,20,opt,name=seuser,proto3" json:"seuser,omitempty" yaml:"seuser"`
	// @inject_tag: yaml:"trim_blocks"
	TrimBlocks *bool `protobuf:"varint,21,opt,name=trim_blocks,json=trimBlocks,proto3,oneof" json:"trim_blocks,omitempty" yaml:"trim_blocks"`
	// @inject_tag: yaml:"unsafe_writes"
	UnsafeWrites bool `protobuf:"varint,22,opt,name=unsafe_writes,json=unsafeWrites,proto3" json:"unsafe_writes,omitempty" yaml:"unsafe_writes"`
	// @inject_tag: yaml:"validate"
	Validate string `protobuf:"bytes,23,opt,name=validate,proto3" json:"validate,omitempty" yaml:"validate"`
	// @inject_tag: yaml:"variable_end_string"
	VariableEndString string `protobuf:"bytes,24,opt,name=variable_end_string,json=variableEndString,proto3" json:"variable_end_string,omitempty" yaml:"variable_end_string"`
	// @inject_tag: yaml:"variable_start_string"
	VariableStartString string `protobuf:"bytes,25,opt,name=variable_start_string,json=variableStartString,proto3" json:"variable_start_string,omitempty" yaml:"variable_start_string"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_template_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Template) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Template) GetMode() *Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *Template) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Template) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Template) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *Template) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *Template) GetBlockEndString() string {
	if x != nil {
		return x.BlockEndString
	}
	return ""
}

func (x *Template) GetBlockStartString() string {
	if x != nil {
		return x.BlockStartString
	}
	return ""
}

func (x *Template) GetCommentEndString() string {
	if x != nil {
		return x.CommentEndString
	}
	return ""
}

func (x *Template) GetCommentStartString() string {
	if x != nil {
		return x.CommentStartString
	}
	return ""
}

func (x *Template) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *Template) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *Template) GetLstripBlocks() bool {
	if x != nil {
		return x.LstripBlocks
	}
	return false
}

func (x *Template) GetNewlineSequence() string {
	if x != nil {
		return x.NewlineSequence
	}
	return ""
}

func (x *Template) GetOutputEncoding() string {
	if x != nil {
		return x.OutputEncoding
	}
	return ""
}

func (x *Template) GetSelevel() string {
	if x != nil {
		return x.Selevel
	}
	return ""
}

func (x *Template) GetSerole() string {
	if x != nil {
		return x.Serole
	}
	return ""
}

func (x *Template) GetSetype() string {
	if x != nil {
		return x.Setype
	}
	return ""
}

func (x *Template) GetSeuser() string {
	if x != nil {
		return x.Seuser
	}
	return ""
}

func (x *Template) GetTrimBlocks() bool {
	if x != nil && x.TrimBlocks != nil {
		return *x.TrimBlocks
	}
	return false
}

func (x *Template) GetUnsafeWrites() bool {
	if x != nil {
		return x.UnsafeWrites
	}
	return false
}

func (x *Template) GetValidate() string {
	if x != nil {
		return x.Validate
	}
	return ""
}

func (x *Template) GetVariableEndString() string {
	if x != nil {
		return x.VariableEndString
	}
	return ""
}

func (x *Template) GetVariableStartString() string {
	if x != nil {
		return x.VariableStartString
	}
	return ""
}

// Mode represents file permissions, supporting both string and numeric formats.
type Mode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: yaml:"value"
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_proto_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_proto_template_proto_rawDescGZIP(), []int{1}
}

func (x *Mode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_template_proto protoreflect.FileDescriptor

const file_proto_template_proto_rawDesc = "" +
	"\n" +
	"\x14proto/template.proto\x12\x05proto\"\xe0\x06\n" +
	"\bTemplate\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1f\n" +
	"\x04mode\x18\x03 \x01(\v2\v.proto.ModeR\x04mode\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x10\n" +
	"\x03src\x18\x05 \x01(\tR\x03src\x12\x1e\n" +
	"\n" +
	"attributes\x18\x06 \x01(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06backup\x18\a \x01(\bR\x06backup\x12(\n" +
	"\x10block_end_string\x18\b \x01(\tR\x0eblockEndString\x12,\n" +
	"\x12block_start_string\x18\t \x01(\tR\x10blockStartString\x12,\n" +
	"\x12comment_end_string\x18\n" +
	" \x01(\tR\x10commentEndString\x120\n" +
	"\x14comment_start_string\x18\v \x01(\tR\x12commentStartString\x12\x16\n" +
	"\x06follow\x18\f \x01(\bR\x06follow\x12\x19\n" +
	"\x05force\x18\r \x01(\bH\x00R\x05force\x88\x01\x01\x12#\n" +
	"\rlstrip_blocks\x18\x0e \x01(\bR\flstripBlocks\x12)\n" +
	"\x10newline_sequence\x18\x0f \x01(\tR\x0fnewlineSequence\x12'\n" +
	"\x0foutput_encoding\x18\x10 \x01(\tR\x0eoutputEncoding\x12\x18\n" +
	"\aselevel\x18\x11 \x01(\tR\aselevel\x12\x16\n" +
	"\x06serole\x18\x12 \x01(\tR\x06serole\x12\x16\n" +
	"\x06setype\x18\x13 \x01(\tR\x06setype\x12\x16\n" +
	"\x06seuser\x18\x14 \x01(\tR\x06seuser\x12$\n" +
	"\vtrim_blocks\x18\x15 \x01(\bH\x01R\n" +
	"trimBlocks\x88\x01\x01\x12#\n" +
	"\runsafe_writes\x18\x16 \x01(\bR\funsafeWrites\x12\x1a\n" +
	"\bvalidate\x18\x17 \x01(\tR\bvalidate\x12.\n" +
	"\x13variable_end_string\x18\x18 \x01(\tR\x11variableEndString\x122\n" +
	"\x15variable_start_string\x18\x19 \x01(\tR\x13variableStartStringB\b\n" +
	"\x06_forceB\x0e\n" +
	"\f_trim_blocks\"\x1c\n" +
	"\x04Mode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB+Z)github.com/mickael-carl/sophons/pkg/protob\x06proto3"

var (
	file_proto_template_proto_rawDescOnce sync.Once
	file_proto_template_proto_rawDescData []byte
)

func file_proto_template_proto_rawDescGZIP() []byte {
	file_proto_template_proto_rawDescOnce.Do(func() {
		file_proto_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_template_proto_rawDesc), len(file_proto_template_proto_rawDesc)))
	})
	return file_proto_template_proto_rawDescData
}

var file_proto_template_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_template_proto_goTypes = []any{
	(*Template)(nil), // 0: proto.Template
	(*Mode)(nil),     // 1: proto.Mode
}
var file_proto_template_proto_depIdxs = []int32{
	1, // 0: proto.Template.mode:type_name -> proto.Mode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_template_proto_init() }
func file_proto_template_proto_init() {
	if File_proto_template_proto != nil {
		return
	}
	file_proto_template_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_template_proto_rawDesc), len(file_proto_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_template_proto_goTypes,
		DependencyIndexes: file_proto_template_proto_depIdxs,
		MessageInfos:      file_proto_template_proto_msgTypes,
	}.Build()
	File_proto_template_proto = out.File
	file_proto_template_proto_goTypes = nil
	file_proto_template_proto_depIdxs = nil
}
